---
name: isotovideo - github action example
# yamllint disable-line rule:truthy
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "registry.opensuse.org/devel/openqa/containers/isotovideo:qemu-x86-jq"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Run isotovideo against test code
        run: isotovideo --exit-status-from-test-results qemu_no_kvm=1 casedir=.
