---
name: isotovideo
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  #test:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: Run isotovideo against test code in happy-path scenario
  #      run: podman run --rm -it -v .:/tests:Z registry.opensuse.org/devel/openqa/containers/isotovideo:qemu-x86 qemu_no_kvm=1 casedir=/tests
