---
name: yamllint
on: [push, pull_request]

permissions:
  contents: read
jobs:
  yamllint:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/containers/os-autoinst_dev
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Validate yamls
        run: |
          yamllint --strict .
